### ISSUE TITLE
Unable to load VOWL in Protégé 5

### ISSUE THREAD

**Issue by abourdon** [VisualDataWeb/ProtegeVOWL#10]
Hi,

I tried to install VOWL as a Protégé but without any success.

Based on the official documentation it says we have to:
- copy the associated Jar to the Protégé's plugins folder
- restart Protégé

Then we should have a new Tab type named as "VOWL".

However, I cannot see any new Tab with this name.

I'm running Protégé v5.2.0 on Mac. Maybe because it is not yet compatible with?

Aurélien

**Comment by abourdon** [comment]
Solution could be related to #8's answer

**Comment by steffen-l** [comment]
Hi @abourdon,

just checked it again, i.e., loaded the plugin from http://vowl.visualdataweb.org/protegevowl.html into the plugins folder of Protégé (v5.2.0). All seem to work fine. You may have to activate the VOWL tab via "Window" -> "Tabs" or can try to restart Protégé (although it should work without any of these actions).

Did you manage to get it running?

**Comment by abourdon** [comment]
Hi @steffen-l,

Unfortunately not. I've just re-test without any result. Note I'm on OSX and tutorial seems to be written on Windows.

On OSX, I put plugin on the `Protégé.app/Contents/Plugins` folder but there is no VOWL entry in the Window/Tab menu:

<img width="461" alt="screen shot 2018-02-06 at 15 25 15" src="https://user-images.githubusercontent.com/1511715/35864652-a9b18b90-0b52-11e8-9bac-ec4ef8ba8d5e.png">

**Comment by ddbd** [comment]
@abourdon 
Indeed, the documentation was written on windows but the procedure is nearly same of linux, just a different path. 

During startup, protégé shows a small shell with all loaded plugins, like you can see for Ubuntu within 
[Issue11](https://github.com/VisualDataWeb/ProtegeVOWL/issues/11). Do you have a similar view within OSX and VOWL is listed within?

As I'm unfamiliar with MacOS I want to ask if you are sure with `Protégé.app/Contents/Plugins`?
The reason for my question is this [link](http://protege-project.136.n4.nabble.com/Installing-Plugins-on-Protege-5-MacOSX-td4665874.html) , it seems there could be a Java Subfolder `Contents/Java/Plugins`.

**Comment by abourdon** [comment]
Hi @ddbd,

The `Protégé.app/Contents/Plugins` folder was already there, and as the Protégé's documentation says that:

> The JAR file must be copied to the plugin folder of Protégé that can be found at:
 <installation_path>\Protege_4.x\plugins\.

So it seemed obvious to me to use it ;-)

But you're right, when moving JAR into the `Protégé.app/Contents/Java/plugins`, now it works.

Maybe documentation could be updated to explain those different locations according to the OS. Anyway, I can close this issue :-)

Thanks for your help!

**Comment by steffen-l** [comment]
Thanks for pointing to this. I added a sentence at http://vowl.visualdataweb.org/protegevowl.html

**Comment by andrewpstern** [comment]
Hi, the above webpage hasn't been updated yet for OSX -- it needs to read:
"(Mac users copy the file to Protégé.app/Contents/Java/plugins.)"

not
"(Mac users copy the file to Protégé.app/Contents/Plugins.)"

**Comment by suljhana** [comment]
The webpage has still not been updated

**Comment by steffen-l** [comment]
Thanks for the reminder. Text has been updated now.
