### ISSUE TITLE
Protege Vowl interface disappeared

### ISSUE THREAD

**Issue by Jinding-X** [VisualDataWeb/ProtegeVOWL#20]
Hi, 

I installed the Vowl plugin in Protege successfully. I accidentally closed the interface of vowl, and now the vowl is empty on my protege. I tried to reinstall Protege and the plugins, but the issue persists. Here is a screenshot of the vowl:
![image](https://github.com/VisualDataWeb/ProtegeVOWL/assets/55116737/a3252e51-aae4-4416-bf68-a7f050663f1e)

**Comment by ddbd** [comment]
Hello Jinding-X,

you can use the "reset selected tab to default state" option within the window section to gain those controls back.
![image](https://github.com/VisualDataWeb/ProtegeVOWL/assets/12701592/83d6514e-e88c-4ccd-aaa6-3237114f601a)

I hope this helps you solving the issue for you.

**Comment by Jinding-X** [comment]
Thank you so much!!! The issue is resolved! I appreciate it.
