### ISSUE TITLE
External Classes/Properties are not loaded

### ISSUE THREAD

**Issue by jgrzebyta** [VisualDataWeb/ProtegeVOWL#6]
I found that if class has name in external file (imported by owl:imports) than that name is not loaded.

**Comment by steffen-l** [comment]
Not all concepts from imported ontologies might be shown in ProtégéVOWL - that's right. Note that ProtégéVOWL has some known limitations and is no longer under active development. A more complete implementation of VOWL is provided by the web application WebVOWL. It also visualizes concepts from imported ontologies - see e.g. http://visualdataweb.de/webvowl/#ontovibe
