### ISSUE TITLE
Visualize selected entity

### ISSUE THREAD

**Issue by jgrzebyta** [VisualDataWeb/ProtegeVOWL#7]
There is no possibility visualised class(es)/predicates selection.

* I my ontology I have several unlinked graphs with different classes.
* Sometimes graph is created using `subclass` predicate. I would like to have possibility to remove that predicate from taking account.

See picture:
![vowl_issue](https://cloud.githubusercontent.com/assets/6738268/22592999/556ecd1e-ea14-11e6-8512-9d738ae286b7.jpg)

**Comment by steffen-l** [comment]
There are no individual filter possibilities in ProtégéVOWL. However, WebVOWL integrates several filters, including one for "solitary subclasses", which might help in your case. Just check out the latest WebVOWL version at http://vowl.visualdataweb.org/webvowl.html
