### ISSUE TITLE
What are plans for that project?

### ISSUE THREAD

**Issue by jgrzebyta** [VisualDataWeb/ProtegeVOWL#8]
Hi,

Are there any plans for that project? I need to visualize my ontology and I do not know if I might update this project or focus on *WebVOWL* in which I might help a bit.

**Comment by steffen-l** [comment]
This project was an initial implementation of the VOWL notation for Protégé. It has some known bugs and limitations, but is no longer under active development, as we focused our development on [WebVOWL](https://github.com/VisualDataWeb/WebVOWL) instead. So better use WebVOWL in your case. Support is always welcome.
